### ISSUE TITLE
super HIGH GPU usage

### ISSUE THREAD

**Issue by waynezhang2021** [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#30]

**Comment by AOx0** [comment]
Part of the problem is that the game attempts to provide the max amount of fps, even tho its not a AAA game. 

Hence, in v0.39.0 there will be an option to set the max frame rate multiplier ratio. 

By default is 1/4. If your monitor can handle 60 fps then the game will have 15 fps.
There will be options to switch between 1/1, 1/2, 1/3 and 1/4 (default)

**Comment by crispeeweevile** [comment]
> Part of the problem is that the game attempts to provide the max amount of fps, even tho its not a AAA game.
> 
> Hence, in v0.39.0 there will be an option to set the max frame rate multiplier ratio.
> 
> By default is 1/4. If your monitor can handle 60 fps then the game will have 15 fps. There will be options to switch between 1/1, 1/2, 1/3 and 1/4 (default)

So the game only runs at 15 fps right now? (technically 1/4 of my monitor speed but that's 60 so...) If that's the case wow, I didn't realize 15 fps looked so great Haha, anyway, why will the options be a multiplier instead of just a number? Seems like the better option would just be a slider (or something) that allowed you to pick "any" fps you want.

edit 1: forgot to type half the message lol
edit 2: forgot to mention edit 1 + fixed a grammar mistake

**Comment by AOx0** [comment]
> So the game only runs at 15 fps right now? (technically 1/4 of my monitor speed but that's 60 so...) If that's the case wow, I didn't realize 15 fps looked so great Haha

No, right now (v0.38.0) uses the monitor's max speed.  But v0.39.0 will enable ratios. 

> Seems like the better option would just be a slider (or something) that allowed you to pick "any" fps you want.

Okay, seems fare. I'll add the option
